# Deploy your Hyas site to GitHub Pages

name: GitHub Pages

on:
  push:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14' # node版本, 更改为你服务器环境的版本

      - name: Install dependencies
        run: npm ci

      - name: Check for linting errors
        run: npm test
        continue-on-error: true

      - name: Build production website
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 如果为私人项目则需要添加授权访问token
          publish_dir: ./public
